# Generated by Django 6.0.4 on 2026-04-28 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="ledgerentry",
            new_name="ledger_entr_merchan_68130b_idx",
            old_name="ledger_merchant_created_idx",
        ),
        migrations.RenameIndex(
            model_name="ledgerentry",
            new_name="ledger_entr_merchan_2b8c6e_idx",
            old_name="ledger_merchant_type_idx",
        ),
        migrations.RenameIndex(
            model_name="ledgerentry",
            new_name="ledger_entr_payout__dfbb9d_idx",
            old_name="ledger_payout_idx",
        ),
    ]
