# Generated by Django 6.0.4 on 2026-04-28 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="bankaccount",
            new_name="bank_accoun_merchan_9fca60_idx",
            old_name="bank_accounts_merchant_primary_idx",
        ),
    ]
