# Generated by Django 6.0.4 on 2026-04-28 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payouts", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="idempotencyrecord",
            new_name="idempotency_merchan_fd3cdf_idx",
            old_name="idempotency_merchant_key_idx",
        ),
        migrations.RenameIndex(
            model_name="payout",
            new_name="payouts_merchan_44832a_idx",
            old_name="payouts_merchant_status_idx",
        ),
        migrations.RenameIndex(
            model_name="payout",
            new_name="payouts_status_ef59be_idx",
            old_name="payouts_status_created_idx",
        ),
        migrations.RenameIndex(
            model_name="payout",
            new_name="payouts_merchan_c7d272_idx",
            old_name="payouts_merchant_idem_idx",
        ),
    ]
